---
site:
  title: Torganized Play
  url: https://docs.paladins-inn.de
  start_page: tp:torganized-play:index.adoc
ui:
  bundle:
    url: src/main/ui-bundle/
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
    - path: CNAME
      contents: |
       docs.paladins-inn.de
asciidoc:
  attributes:
    sectanchors: true
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    imagesoutdir: temp_image/
  extensions:
    - asciidoctor-plantuml

output:
  dir: /site

content:
  sources:
    - url: .
      start_path: src/main/docs/torganized-play
      branches: main
      version: false
    - url: .
      start_path: src/main/docs/dcis
      branches: main
      version: false
    - url: .
      start_path: src/main/docs/architecture
      branches: main
      version: false
