---
site:
  title: Kaiserpfalz-EDV Software
  url: https://docs.kaiserpfalz-edv.github.io/
  start_page: current@kes:ROOT:index.adoc
  robots: |
    User-agent: *
    Disallow: /impressum.html

content:
  sources:
    - url: .
      branches: *
      version: false
    - url: https://github.com/KaiserpfalzEDV/kp-commons.git
      start_path: docs
      branches: *
      version: true
    - url: https://github.com/KaiserpfalzEDV/kp-commons.git
      start_path: modules/kp-users-root/docs
      branches: *
      version: true

urls:
  redirect_facility: static

ui:
  bundle:
    url: ui-bundle/
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
    - path: CNAME
      contents: |
        docs.kaiserpfalz-edv.github.io

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: '@antora/pdf-extension'

asciidoc:
  attributes:
    toc: ''
    toclevels: 5
    sectnums: ''
    sectnumlevels: 5
    sectanchors: true
    kroki-server-url: https://kroki.apps.kali.kaiserpfalz-edv.de
    kroki-fetch-diagram: true
    imagesoutdir: temp_image/
  extensions:
    - 'asciidoctor-kroki'

runtime:
  fetch: true
  log:
    level: info
    format: pretty