---
site:
  title: Paladins Inn Software
  url: https://docs.paladins-inn.de
  start_page: pi:commons:index.adoc
  robots: |
    User-agent: *
    Disallow: /impressum.html

content:
  sources:
    - url: .
      branches: main
      version: false
    - url: https://github.com/Paladins-Inn/torganized-play-architecture.git
      start_path: src/main/docs/torganized-play
      branches: main
      version: false
    - url: https://github.com/Paladins-Inn/torganized-play-architecture.git
      start_path: src/main/docs/dcis
      branches: main
      version: false
    - url: https://github.com/Paladins-Inn/torganized-play-architecture.git
      start_path: src/main/docs/architecture
      branches: main
      version: false

urls:
  redirect_facility: static

ui:
  bundle:
    url: ui-bundle/
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
    - path: CNAME
      contents: |
       docs.paladins-inn.de

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: '@antora/pdf-extension'

asciidoc:
  attributes:
    sectanchors: true
    plantuml-server-url: https://kroki.kaiserpfalz-edv.de/plantuml
    plantuml-fetch-diagram: true
    imagesoutdir: temp_image/
  extensions:
    - 'asciidoctor-plantuml'

runtime:
  fetch: true
  log:
    level: info
    format: pretty