---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "simple-service.fullname" . }}-db-secret
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
stringData:
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_PASSWD: {{ .Values.database.password | quote }}
  POSTGRES_HOST: {{ include "simple-service.fullname" . }}-database
  POSTGRES_PORT: {{ .Values.database.service.port | quote }}