apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-service.fullname" . }}
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: sql
      port: {{ .Values.service.port }}
      targetPort: sql
      protocol: TCP
  selector:
    {{- include "simple-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
