apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-service.fullname" . }}-service
  labels:
    {{- include "simple-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "simple-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: service
